### copy() 메서드는 서로 다른 객체로 복사

In [1]:
### 얕은 복사: 같은 주소값을 가지는 채로 복사
### 깊은 복사: import copy, .deepcopy() 사용
### 전혀 다른 메모리 공간을 할당하여 복사. 값은 같으나(==) 객체는 다름

In [2]:
easy_list = [[1, 2, 3, 4, 5], [3, 4]]
for item in easy_list:
    for i in item:
        print(i)

1
2
3
4
5
3
4


### add(), remove(), discard(), pop()
### set.clear(), .len(), .union, .intersection, .difference

In [3]:
score = 90
'A' if 90<score<=100 else 'B' if 80<score else 'C'

'B'

In [14]:
# class
class Student:
    def __init__(self):
        self.hello = "안녕하세요."
        
    def greeting(self):
        print(self.hello)

In [15]:
#stu_a, stu_b는 독립적으로 존재
stu_a = Student()
stu_b = Student()

stu_a.name = "학생A"
stu_a.hello = "안녕하세요."

stu_a.greeting()
print(stu_a.hello)
print(stu_a.name)
print(stu_b.hello)

안녕하세요.
안녕하세요.
학생A
안녕하세요.


In [19]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [20]:
p1 = Person("name1", 40)
p2 = Person("name2", 32)

In [21]:
p1.__dict__

{'name': 'name1', 'age': 40}

In [23]:
p2.__dict__

{'name': 'name2', 'age': 32}

In [26]:
class Person1:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")

In [53]:
maria = Person1("마리아", 23, "서울시 마포구")
maria.greeting()
maria.__dict__

NameError: name 'Person1' is not defined

In [54]:
class Person2:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address
        
    def info(self):
        print(f"이름: {self.name}\n나이: {self.age}\n주소: {self.address}")

maria = Person2(input("이름은 무엇인가요?"), input("나이는 무엇인가요?"), input("주소는 무엇인가요?"))
maria.info()

이름은 무엇인가요? 마리아
나이는 무엇인가요? 20
주소는 무엇인가요? 강남


이름: 마리아
나이: 20
주소: 강남


### 비공개 속성: '인스터스.속성 = 값'을 통해 인스턴스의 속성 값을 변경 못하도록 막는다. 속성 앞에 던더(__)를 붙이면 비공개 속성 된다.
### 메서드도 던더 붙이면 비공개 메서드

In [52]:
class ClassName:
    def __init__(self, param1, param2):
        self.attr1 = param1
        self.__attr2 = param2 # 비공개 속성

In [63]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet # 비공개 속성
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)
        
    def pay(self, amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount
        print("이제 {0}원 남았네요.".format(self.__wallet))

In [65]:
lsj = Person3("이선주", 98, "경기도 성남", 20000)
print(lsj.name)
print(lsj.age)
print(lsj.address)
print(lsj.wallet)

이선주
98
경기도 성남


AttributeError: 'Person3' object has no attribute 'wallet'

In [66]:
lsj.amount()

20000


In [67]:
maria = Person3("마리아", 20, "서초구", 10000)
maria.__wallet -= 10000 # 클래스 바깥에서 비공개 속성에 접근하면 에러 발생

AttributeError: 'Person3' object has no attribute '__wallet'

In [68]:
lsj.pay(10000)
lsj.amount()

이제 10000원 남았네요.
10000


In [78]:
class Annie:
    def __init__(self, health, mana, AP):
        self.health = health
        self.mana = mana
        self.AP = AP
    
    def tibbers(self):
        self.dammage = self.AP * 0.65 + 400
        print(f"티버: 피해량 {self.dammage}")
        
health, mana, AP = map(float, input("체력, 마나, AP를 입력하세요: ").split(" "))
annie1 = Annie(health, mana, AP)
annie1.tibbers()

체력, 마나, AP를 입력하세요:  511.68 334.0 298


티버: 피해량 593.7


### numpy
### 숫자 데이터를 효과적으로 다룰 수 있다. 데이터 과학 및 데이터 분석에 많이 사용 됨
### 배열이란 순서가 있는 같은 정류의 데이터가 저장되는 자료형을 말함

In [79]:
import numpy as np

### ndarray: n-dimensional array
shape: (4, )

In [87]:
shape:(4,)
ar = np.array([_ for _ in range (10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
ar.shape

(10,)

In [91]:
!conda list

# packages in environment at C:\Users\peter\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0    

In [93]:
import numpy as np
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
ar.shape

(10,)

In [95]:
type(ar)

numpy.ndarray

### 정수와 실수가 혼합된 ndaaray객체를 생성하면 모두 실수 타입으로 선언됨(표현 범위가 더 큰 자료형으로 벼환)

In [96]:
ar2 = np.array([0.1, 5, 6, 12, 0.5])
ar2

array([ 0.1,  5. ,  6. , 12. ,  0.5])

In [97]:
ar.dtype

dtype('int32')

In [98]:
ar2.dtype

dtype('float64')

01010101 -> 8bit == 1byte

In [99]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') # int8*8 bit
ar3

array([3, 6, 9], dtype=int64)

In [103]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [109]:
ar5 = np.array(["가나다라마", "바사아", "자", "차카"], 'U5')
print(ar5)
print(ar5.dtype) # 최대 5글자의 유니코드 자료형
ar5_1 = np.array(["가나다라마", "바사아", "자", "차카"], 'U8')
print(ar5_1)
print(ar5_1.dtype) # 최대 8글자의 유니코드 자료형

['가나다라마' '바사아' '자' '차카']
<U5
['가나다라마' '바사아' '자' '차카']
<U8


In [113]:
x = np.array([1, 2, 3], dtype='f')
x.dtype
x[0] + x[1]

3.0

In [112]:
x = np.array([1, 2, 3], dtype='U')
x.dtype
x[0] + x[1]

'12'

### nan, inf, -inf

In [115]:
np.array([0, 1, -1, 0])/np.array([1, 0, 0, 0])

C:\Users\peter\AppData\Local\Temp\ipykernel_15976\3180148017.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0])/np.array([1, 0, 0, 0])
C:\Users\peter\AppData\Local\Temp\ipykernel_15976\3180148017.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0])/np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [116]:
np.log(0)

C:\Users\peter\AppData\Local\Temp\ipykernel_15976\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [117]:
np.exp(-np.inf)

0.0

### 넘파이 배열 객체는 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원한다.

In [118]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### 넘파이 배열 객체의 벡터화 연산을 사용하여 for 반복문 없이 간단하게 한번의 연산식으로 표현 가능. 속도도 빠르다

In [119]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [121]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [124]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(2 * a + b)
print(a == 2)
print(b>10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


### 수학에서 2차원 배열을 행렬(matrix)라고 한다.

In [127]:
c= np.array([[0, 1 ,2], [3, 4, 5]]) # 2x3 array
print(c)
print(c.shape)
print(len(c))
print(len(c[0]))

[[0 1 2]
 [3 4 5]]
(2, 3)
2
3


In [128]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열 만들기. 깊이 * 행 * 열 의 모양 갖는다.

In [134]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]]])

print(d)
print(d.ndim)
print(d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
3
(2, 3, 4)


In [138]:
a = np.array([_ for _ in range(5)])
print(a)
print(a[2])
print(a[-1])

[0 1 2 3 4]
2
4


In [141]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)
print(a[0][0])
print(a[-1][-1])

[[1, 2, 3], [4, 5, 6]]
1
6


In [146]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[0, :])
print(a[:, 1])
print(a[1, 1:])
print(a[:2, :2])

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [147]:
np.array([_ for _ in range(8)]).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [149]:
m = np.array([_ for _ in range(15)]).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
print(m[1, 2])
print(m[2, 4])
print(m[1, 1:3])
print(m[1:3, 2])
print(m[:2, 3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


### numpy의 배열 생성 메서드

In [171]:
a = np.zeros(5)
print(a)
c = np.zeros((5, 2), dtype="i") # i == int
c

[0. 0. 0. 0. 0.]


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [172]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [174]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" # 유니코드 최대 4글자기 때문에 ABCD까지
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [176]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [177]:
f = np.ones_like(b, dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [179]:
g = np.empty((4, 3))
g

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313],
       [2.54639495e-313, 2.97079411e-313, 3.39519327e-313],
       [3.81959242e-313, 4.24399158e-313, 4.66839074e-313]])

In [180]:
np.arange(10) # array의 range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

### linspace 명령 시작, 끝(포함), 구간

In [182]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [186]:
ex = np.linspace(0, 100, 21)
ex

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [187]:
ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

### 전치(transpose) 행과 열을 바꿈. T로 수행. 메서드가 아닌 속성이다

In [193]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()
print(A.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [198]:
# 배열의 크기 변형
ex3 = np.arange(12)
ex3.reshape(3, 4)
ex3.reshape(3, -1) # 뒤를 -1로 하면 알아서 맞춰줘라

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [202]:
ex3 = np.arange(12)
ex3.reshape(2,

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [203]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [205]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [204]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 배열 연결 hstack, vstack, dstack, stack, r__, c__, tile, hstack

In [208]:
# hstack은 행의 수가 같은 두 개 이사으이 배열을 옆으로 연결
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [209]:
a2 = np.zeros((2, 2))
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [210]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [211]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [213]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [214]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [215]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [216]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [217]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [218]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [219]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [221]:
c.shape

(2, 3, 4)

In [222]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

### r_ 메서드는 hstack 명령과 비슷하게 배열을 좌우로 연결합니다. 다만 메서드임에도 불구하고 소괄호()를 사용하지 않고 인덱싱과 같이 대괄호[]를 사용합니다. 이런 특수 메서드를 인데서(indexer)라고 합니다.

In [224]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])] # row

array([1, 2, 3, 4, 5, 6])

### c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결합니다. 만약 1차원 배열을 연결하면 2차원 배열이 됩니다.

In [227]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

### tile 동일한 배열을 반복하여 연결

In [230]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [229]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [235]:
a = np.zeros((3, 3))
print(a)
b = np.ones((3, 2))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [242]:
a1 = np.hstack([a, b])
a1

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [256]:
c = np.arange(10, 151, 10)
c.reshape(3, 5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [254]:
e = np.vstack([a1, c])
e

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 15